project:
  type: website

website:
  title: "PK End to End Examples"
  navbar:
    pinned: true
    collapse: false
    background: primary
    search: true
    right:
      - icon: slack
        href: https://app.slack.com/client/T028PB489D3/
        aria-label: Slack
      - icon: github
        href: https://github.com/pharmaverse/e2e_pk
        aria-label: Repository      
  sidebar:
    - id: sidebar
      style: docked
      collapse-level: 1
      logo: images/admiral.png
      border: true
      contents:
      - adpc.qmd
      - adppk.qmd

  favicon: images/pharmaverse-favicon.png
  

format:
  html:
    theme:
      light:
        - flatly
      dark:
        - darkly
    css: styles.css
    toc: true

editor: visual

