project:
  type: website

website:
  title: "PK End to End Examples"
  navbar:
    left:
      - adppk.qmd
      - adpc.qmd
  favicon: images/pharmaverse-favicon.png
  

format:
  html:
    theme:
      light:
        - flatly
      dark:
        - darkly
    css: styles.css
    toc: true

editor: visual

